### ISSUE TITLE
Go to default root host of domain

### ISSUE THREAD

**Issue by Gitoffthelawn** [PerfectSlayer/scrollupfolder#47] opened 2018-03-24 19:58 UTC
Several times recently, I've needed to go to the default "root" host of a domain.

So let's say I'm on `gitoffthelawn.github.com`.  I then want to go to `www.github.com`.

Can you add it to the top of the list in the scrollupfolder dropdown?

For example:

```
www.github.com
gitoffthelawn.github.com
gitoffthelawn.github.com/folder
gitoffthelawn.github.com/folder/page.html

```

**Comment by PerfectSlayer** [comment] 2018-03-27 17:02
Hi @Gitoffthelawn ffthelawn 

If fact, it is the expected behavior. As the issue #10 points out, the `www` sub-domain is not a top domain. In fact, your example demonstrates it: `www.github.com` is not an upper domain of `gitoffthelawn.github.com`.

Usually, when the `www` is the top domain, going to `domain.com` redirects to `www.domain.com` so it should work as you expect. Otherwise, it seems good to me to go to `domain.com` and not `www.domain.com` if they are different.

What do you think about it?

**Comment by Gitoffthelawn** [comment] 2018-03-28 06:03
Hi!

I agree.  Well, almost completely.  Sometimes `domain.com` won't work, and you need to go to `www.domain.com`.  I suppose both could be listed, with `domain.com` on top.

I think there may be a bug though.  If you go to `http://forum.freecommander.com/`, and then press the extension's button, neither `freecommander.com` nor `www.freecommander.com` is listed as an option.

**Comment by PerfectSlayer** [comment] 2018-03-29 17:26
Hum, if we add the `www.domain.com`, it should be on top:
1. `www.domain.com`
1. `domain.com`
1. `forum.domain.com`
1. `forum.domain.com/members/`

Because the logical parent of `forum.domain.com` is `domain.com` and `www.domain.com` should be added as first default element if not already present in the list.

**Comment by Gitoffthelawn** [comment] 2018-03-30 05:44
Ya, you're probably right... although it would look prettier in the other order. :)

Of course, your logic is spot on.

BTW, could you reproduce the bug on `freecommander.com` mentioned above (or is it just functionality not implemented yet)?

**Comment by PerfectSlayer** [comment] 2018-03-31 07:42
Sorry, I did not catch the `freecommander.com` issue.

I just setup an environment and give it a try. It looks like it work for me:
![2018-03-31-093801_1366x735_scrot](https://user-images.githubusercontent.com/1766222/38161014-9c9fff74-34c7-11e8-9437-6b38eb5124bb.png)

Do you have the same result?

**Comment by Gitoffthelawn** [comment] 2018-03-31 07:54
Weird.  I get a completely different result.  Mine doesn't list `http://freecommander.com`.

Tested on Win7 with FF60b8.

**Comment by PerfectSlayer** [comment] 2018-03-31 08:04
Yes weird… I also run Firefox 60.0b8 (but on ChromeOS using crouton to run Debian. That's an other story!)

Maybe we could try to find what differs from my setup:
* Do you modified the add-on?
* What are the *exact* URL your test?
* What are your add-on settings (they are all checked by default)?

**Comment by Gitoffthelawn** [comment] 2018-03-31 08:25
Just tried it in a new FF profile.  Same result.  8-)

**Comment by PerfectSlayer** [comment] 2018-03-31 10:11
When you said "same result", it means same result as me (working) or same result as your default profile (not working)? 😥

**Comment by PerfectSlayer** [comment] 2018-03-31 12:24
💡 ! Could you try to:
1. Disable `Parse domain option`,
2. Reboot Firefox,
3. Enable `Parse domain option`,
4. Test http://forum.freecommander.com again.

It might be a default setting value which is not applied.

**Comment by Gitoffthelawn** [comment] 2018-03-31 17:26
> When you said "same result", it means same result as me (working) or same result as your default profile (not working)?

LOL.  That was ambiguous!  Same result as my default profile (not working).

> Could you try to...

I don't see a `Parse domain` option in v6.01.  I do see a `Parse anchor` option.  I tuned that off.  Restarted FF.  Turned it on.  Restarted FF.  Tested.  Still getting same result as I was getting before (not working).

**Comment by PerfectSlayer** [comment] 2018-04-01 06:26
Okay, I see the issue here… I did not release the 6.1 version with the parsing domain option!
I just tried it and I found some bugs remains:
- Error while parsing «_two dots domains_» (ex .co.uk),
- Error while parsing IPv4 address. 

I would really like to code unit tests before releasing this kind of feature but I don't know how to make it for WebExtensions...

**Comment by Gitoffthelawn** [comment] 2018-04-01 07:30
I had a hunch we were using different versions of the extension! :)

**Comment by Gitoffthelawn** [comment] 2018-04-01 19:01
Woohoo! :)

**Comment by PerfectSlayer** [comment] 2018-04-03 16:50
Here it is! I just found a network connection to push it to GitHub: fafe7db72b8e605d37f6833b3d57bcaf52a1d7b9
You could check the expected behavior reading the [test cases](https://github.com/PerfectSlayer/scrollupfolder/blob/master/test/test.js) 😉 

I now need to update documentation and make a new release.
I also would like to ship the PR #44 but I don't know when it will be ready.

**Comment by PerfectSlayer** [comment] 2018-04-16 10:15
As the version was approved on AMO, I close the issue!

**Closed by PerfectSlayer** 2018-04-16 10:15 UTC
Labels: enhancement, question
